[package]
name = "jitfive"
version = "0.1.0"
edition = "2021"

[dependencies]
ordered-float = "3"
parse_int = "0.6"
thiserror = "1"

clap = { version = "3.2.6", features = ["derive"] }
image = { version = "0.24", default-features = false, features = ["png"] }
