[package]
name = "fidget"
version = "0.1.4"
edition = "2021"
license = "MPL-2.0"
repository = "https://github.com/mkeeter/fidget"
description = "Infrastructure for complex closed-form implicit surfaces"
authors = ["Matt Keeter <matt.j.keeter@gmail.com"]
readme = "../README.md"

[dependencies]
arrayvec = "0.7"
document-features = "0.2"
num-derive = "0.3"
num-traits = "0.2"
ordered-float = "3"
static_assertions = "1"
thiserror = "1"

# JIT
dynasmrt = { version = "2.0", optional = true }
libc = { version = "0.2", optional = true }

# Rhai
rhai = { version = "1.10", optional = true, features = ["sync"] }

# Render
nalgebra = { version = "0.31", optional = true }

[features]
default = ["jit", "rhai", "render", "mesh"]

## Enables fast evaluation via a JIT compiler.  This is exposed in the
## [`fidget::jit`](crate::jit) module, and is supported on
## `aarch64-apple-darwin`, `aarch64-unknown-linux-*`, and
## `x86_64-unknown-linux-*`.  There's no way to disable the feature on other
## platforms ([Cargo issue](https://github.com/rust-lang/cargo/issues/1197));
## users will have to disable it manually via `default-features = false`.
jit = ["dep:dynasmrt", "dep:libc"]

## Enable [Rhai](https://rhai.rs/) bindings, in the
## [`fidget::rhai`](crate::rhai) module
rhai = ["dep:rhai"]

## Enable 2D and 3D rendering, in the [`fidget::render`](crate::render) module
render = ["dep:nalgebra"]

## Enable 3D meshing, in the [`fidget::mesh`](crate::mesh) module
mesh = ["dep:nalgebra"]

## Enable `eval-tests` if you're writing your own evaluator family and want to
## unit-test it.  When enabled, the crate exports a set of macros to test each
## evaluator type, e.g. `float_slice_tests!(...)`.
eval-tests = []

## On Linux, this feature uses `mprotect` to prevent JIT buffers from being both
## writable and executable at the same time.  This is best practice from a
## security perspective, but incurs a 25% slowdown.
write-xor-execute = []
