[package]
name = "fidget"
version = "0.1.0"
edition = "2021"

[dependencies]
arrayvec = "0.7"
num-derive = "0.3"
num-traits = "0.2"
ordered-float = "3"
thiserror = "1"

# JIT
dynasmrt = { version = "1.2.3", optional = true }
libc = { version = "0.2", optional = true }

# Rhai
rhai = { version = "1.10", optional = true }

# Render
nalgebra = { version = "0.31", optional = true }

[features]
default = ["jit", "rhai", "render"]

jit = ["dynasmrt", "libc"]
rhai = ["dep:rhai"]
render = ["nalgebra"]

# Enable `eval-tests` if you're writing your own objects which implement the
# `[Point|Interval|FloatSlice|Grad]EvalT` trait(s) and want to unit test them
eval-tests = []
