[package]
name = "fidget"
version = "0.1.0"
edition = "2021"

[dependencies]
arrayvec = "0.7"
dynasmrt = "1.2.3"
itertools = "0.10.4"
log = "0.4"
num-derive = "0.3"
num-traits = "0.2"
ordered-float = "3"
thiserror = "1"
