[package]
name = "fidget"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fidget-core = { path = "../fidget-core" }
fidget-render = { path = "../fidget-render" }
fidget-rhai = { path = "../fidget-rhai" }
