[package]
name = "demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jitfive = { path = "../jitfive" }
env_logger = "0.9"

clap = { version = "3.2.6", features = ["derive"] }
image = { version = "0.24", default-features = false, features = ["png"] }
inkwell = { git = "https://github.com/TheDan64/inkwell", branch = "master", features = ["llvm14-0"] }
piet-gpu-hal = { git = "https://github.com/linebender/piet-gpu" }
