[package]
name = "fidget-core"
version = "0.1.0"
edition = "2021"

[dependencies]
arrayvec = "0.7"
dynasmrt = "1.2.3"
libc = "0.2"
memmap2 = "0.5.7"
num-derive = "0.3"
num-traits = "0.2"
ordered-float = "3"
thiserror = "1"
