name: Build & Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose --package fidget --no-default-features --features rhai,render
    - name: Run tests
      run: cargo test --verbose --package fidget --no-default-features --features rhai,render
